# Server tests for block-diffusion (canvas) models such as DiffusionGemma.
#
# These run against the tiny random-weight test model in ../assets/tiny-diffusion-gemma-f32.gguf
# (generated by ../make_tiny_diffusion_gemma.py - fully synthetic config/tokenizer/weights, nothing
# derived from any released Gemma artifact). The model produces garbage-but-deterministic canvases
# over a small word alphabet plus the "<channel|>" scaffold-close marker, which is exactly what the
# server-side block-diffusion plumbing needs to be testable:
#
#   - startup gating on the GGUF diffusion.canvas_length key (+ n_parallel clamp warning)
#   - single-block SSE /completion (one partial per denoised block)
#   - multi-block n_predict (block-autoregressive commit)
#   - stop strings across a block edge, on the raw and the scaffold-stripped paths
#   - /v1/chat/completions parity with /completion
#   - autoregressive models keep taking the old code paths (no clamp, no diffusion logs)
#
# Because the weights are random, the tests never assert specific text; expectations are computed
# from a first (deterministic, seeded) run against the same server instance.

import os
import re

import pytest
from utils import *

ASSETS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets")
DIFFUSION_GGUF = os.environ.get(
    "LLAMA_SERVER_TEST_DIFFUSION_GGUF",
    os.path.join(ASSETS_DIR, "tiny-diffusion-gemma-f32.gguf"),
)

CANVAS = 32           # diffusion.canvas_length of the test model
MARKER = "<channel|>" # scaffold-close marker (single vocab token, rendered)

# the chat template embedded in the test model GGUF renders exactly this shape, so raw /completion
# requests using this prompt are token-identical to /v1/chat/completions with one user message
PROMPT = "<|turn>user\nsay something<turn|>\n<|turn>model\n"

server: ServerProcess


def diffusion_server() -> ServerProcess:
    s = ServerProcess()
    s.model_file = DIFFUSION_GGUF
    s.model_hf_repo = None
    s.model_hf_file = None
    s.model_alias = "tiny-diffusion-gemma"
    s.n_ctx = 512
    s.jinja = True
    s.seed = 42
    return s


@pytest.fixture(autouse=True)
def create_server():
    global server
    server = diffusion_server()


def completion(data: dict) -> dict:
    res = server.make_request("POST", "/completion", data=data)
    assert res.status_code == 200
    return res.body


def stream_blocks(data: dict) -> tuple[list[str], dict]:
    """Run a streamed /completion; return (per-block content parts, final event)."""
    parts = []
    final = None
    for ev in server.make_stream_request("POST", "/completion", data={**data, "stream": True}):
        assert "stop" in ev
        if ev["stop"]:
            final = ev
        elif ev.get("content"):
            parts.append(ev["content"])
    assert final is not None
    return parts, final


def expected_stripped(blocks: list[str]) -> str:
    """Reference implementation of the per-block scaffold extraction (mirrors
    update_slots_diffusion): the visible stream restarts after the LAST channel-close;
    if no close is ever generated the whole held canvas is flushed."""
    held = ""
    out = ""
    seen_close = False
    for b in blocks:
        p = b.rfind(MARKER)
        if p != -1:
            out = b[p + len(MARKER):]
            held = ""
            seen_close = True
        elif seen_close:
            out += b
        else:
            held += b
    return out if seen_close else held


#
# startup gating + n_parallel clamp
#

def test_startup_gating_and_n_parallel_clamp():
    global server
    server.n_slots = 2  # must be clamped to 1 for canvas models
    os.makedirs(TMP_DIR, exist_ok=True)
    server.log_path = os.path.join(TMP_DIR, "test_diffusion_gating.log")
    server.start()

    with open(server.log_path) as f:
        log = f.read()
    assert f"block-diffusion canvas model detected, canvas_length = {CANVAS}" in log
    assert "forcing n_parallel = 1" in log
    assert "diffusion_eb:" in log

    res = server.make_request("GET", "/props")
    assert res.status_code == 200
    assert res.body["total_slots"] == 1


def test_prompt_canvas_must_fit_one_ubatch():
    global server
    server.start()
    # n_ctx = n_ubatch = 512; a prompt longer than 512 - CANVAS tokens must be rejected
    res = server.make_request("POST", "/completion", data={
        "prompt": "x " * 600,
        "n_predict": CANVAS,
        "seed": 42,
    })
    assert res.status_code == 400
    assert "ubatch" in str(res.body)


#
# single-block SSE /completion
#

def test_single_block_sse_completion():
    global server
    server.start()
    data = {"prompt": PROMPT, "n_predict": CANVAS, "seed": 42, "diffusion_raw": True}

    parts, final = stream_blocks(data)
    # one denoised block = exactly ONE content-bearing SSE partial
    assert len(parts) == 1
    assert len(parts[0]) > 0
    assert final["stop_type"] == "limit"
    assert final["tokens_predicted"] == CANVAS
    assert final["tokens_evaluated"] > 0
    assert "timings" in final
    assert final["timings"]["predicted_n"] == CANVAS

    # non-stream same-seed run returns the identical content
    body = completion(data)
    assert body["content"] == parts[0]
    assert body["tokens_predicted"] == CANVAS


#
# multi-block n_predict
#

def test_multi_block_n_predict():
    global server
    server.start()
    n_predict = 2 * CANVAS + CANVAS // 2  # 2.5 blocks
    data = {"prompt": PROMPT, "n_predict": n_predict, "seed": 42, "diffusion_raw": True}

    parts, final = stream_blocks(data)
    assert len(parts) == 3  # block-AR commit: 32 + 32 + 16 tokens
    assert final["stop_type"] == "limit"
    assert final["tokens_predicted"] == n_predict

    # deterministic block commit: the first block of a longer run equals the single-block run
    one, _ = stream_blocks({"prompt": PROMPT, "n_predict": CANVAS, "seed": 42, "diffusion_raw": True})
    assert parts[0] == one[0]

    # non-stream equals assembled stream
    body = completion(data)
    assert body["content"] == "".join(parts)
    assert body["tokens_predicted"] == n_predict


#
# stop strings across a block edge
#

def test_stop_string_across_block_edge_raw():
    global server
    server.start()
    base = {"prompt": PROMPT, "n_predict": 2 * CANVAS, "seed": 42, "diffusion_raw": True}

    # discovery run: get the two blocks, then build a stop string that straddles the edge
    parts, _ = stream_blocks(base)
    assert len(parts) == 2
    b1, b2 = parts
    full = b1 + b2

    stop = None
    for k in range(3, 9):
        for m in range(3, 9):
            cand = b1[-k:] + b2[:m]
            if full.find(cand) == len(b1) - k:  # first occurrence is exactly at the edge
                stop = cand
                break
        if stop:
            break
    assert stop is not None, "could not build an edge-straddling stop string from the blocks"
    expected = full[: full.find(stop)]

    # non-stream: truncated at the stop string that only completes in block 2
    body = completion({**base, "stop": [stop]})
    assert body["stop_type"] == "word"
    assert body["stopping_word"] == stop
    assert body["content"] == expected

    # stream: the partial match at the block 1 edge is held back, then resolved by block 2
    parts_s, final_s = stream_blocks({**base, "stop": [stop]})
    assert "".join(parts_s) == expected
    assert final_s["stop_type"] == "word"


def test_stop_string_scaffold_stripped():
    global server
    server.start()
    raw = {"prompt": PROMPT, "n_predict": CANVAS, "seed": 42, "diffusion_raw": True}

    raw_text = completion(raw)["content"]
    stripped = completion({**raw, "diffusion_raw": False})

    # the raw completion path emits only the text after the LAST channel-close
    expect = expected_stripped([raw_text])
    assert stripped["content"] == expect
    # tokens_predicted keeps counting the scaffold tokens
    assert stripped["tokens_predicted"] == CANVAS

    if MARKER not in raw_text or len(expect.split()) < 2:
        pytest.skip("seed 42 canvas has no usable scaffold tail for the stop-string sub-case")

    # a stop string inside the stripped tail truncates the STRIPPED text
    words = expect.split()
    stop = words[len(words) // 2]
    truncated = completion({**raw, "diffusion_raw": False, "stop": [stop]})
    assert truncated["stop_type"] == "word"
    assert truncated["stopping_word"] == stop
    assert truncated["content"] == expect[: expect.find(stop)]


def test_stop_string_scaffold_stripped_across_block_edge():
    global server
    server.start()

    # find a seed where block 1 closes the scaffold (non-empty tail) and block 2 has no close
    # (a close in block 2 would restart the visible stream instead of appending);
    # each probe is one tiny 2-block generation, and the result is deterministic per build
    found = None
    for seed in range(1, 81):
        parts, _ = stream_blocks({
            "prompt": PROMPT, "n_predict": 2 * CANVAS, "seed": seed, "diffusion_raw": True,
        })
        assert len(parts) == 2
        b1, b2 = parts
        tail = expected_stripped([b1])
        if MARKER in b1 and len(tail) >= 3 and MARKER not in b2:
            found = (seed, tail, b2)
            break
    assert found is not None, "no usable seed found for the stripped block-edge stop case"
    seed, tail, b2 = found

    visible = tail + b2  # the stripped stream across both blocks
    stop = None
    for k in range(3, 9):
        for m in range(3, 9):
            cand = tail[-k:] + b2[:m]
            if visible.find(cand) == len(tail) - k:
                stop = cand
                break
        if stop:
            break
    assert stop is not None, "could not build an edge-straddling stop string from the stripped stream"
    expected = visible[: visible.find(stop)]

    body = completion({
        "prompt": PROMPT, "n_predict": 2 * CANVAS, "seed": seed, "stop": [stop],
    })
    assert body["stop_type"] == "word"
    assert body["stopping_word"] == stop
    assert body["content"] == expected


#
# /v1/chat/completions parity
#

def test_chat_completions_parity():
    global server
    server.start()

    # the raw /completion prompt above is exactly what the model's chat template renders for this
    # message, so the chat endpoint must produce the identical canvas for the same seed
    raw = completion({"prompt": PROMPT, "n_predict": CANVAS, "seed": 42, "diffusion_raw": True})

    res = server.make_request("POST", "/v1/chat/completions", data={
        "messages": [{"role": "user", "content": "say something"}],
        "max_tokens": CANVAS,
        "seed": 42,
    })
    assert res.status_code == 200
    choice = res.body["choices"][0]
    assert choice["finish_reason"] == "length"
    # the chat path stays raw - its parser owns any scaffold splitting downstream
    assert choice["message"]["content"] == raw["content"]
    assert res.body["usage"]["completion_tokens"] == CANVAS
    assert res.body["usage"]["prompt_tokens"] == raw["tokens_evaluated"]

    # streamed chat completion assembles to the same content
    # (parsed directly: finish_reason arrives on the choice of the last chunk, same as AR models)
    content = ""
    finish_reason = None
    for chunk in server.make_stream_request("POST", "/v1/chat/completions", data={
        "messages": [{"role": "user", "content": "say something"}],
        "max_tokens": CANVAS,
        "seed": 42,
        "stream": True,
    }):
        for ch in chunk.get("choices", []):
            content += ch.get("delta", {}).get("content") or ""
            finish_reason = ch.get("finish_reason") or finish_reason
    assert content == raw["content"]
    assert finish_reason == "length"


#
# queued concurrency on the single slot
#

def test_concurrent_requests_queue_on_single_slot():
    global server
    server.start()

    def one(seed: int):
        return server.make_request("POST", "/completion", data={
            "prompt": PROMPT, "n_predict": CANVAS, "seed": seed, "diffusion_raw": True,
        })

    results = parallel_function_calls([(one, (42,)), (one, (43,))])
    assert all(r.status_code == 200 for r in results)
    assert all(r.body["tokens_predicted"] == CANVAS for r in results)


#
# autoregressive models: no behavior change
#

def test_ar_model_no_regression():
    global server
    server = ServerPreset.tinyllama2()
    server.n_slots = 2
    os.makedirs(TMP_DIR, exist_ok=True)
    server.log_path = os.path.join(TMP_DIR, "test_diffusion_ar_noregression.log")
    server.start()

    with open(server.log_path) as f:
        log = f.read()
    # none of the diffusion gating may trigger for an AR model
    assert "block-diffusion" not in log
    assert "forcing n_parallel" not in log
    assert "diffusion_eb" not in log

    res = server.make_request("GET", "/props")
    assert res.status_code == 200
    assert res.body["total_slots"] == 2  # -np is NOT clamped for AR models

    # the reference completion from test_completion.py behaves as before
    res = server.make_request("POST", "/completion", data={
        "n_predict": 8,
        "prompt": "I believe the meaning of life is",
        "seed": 42,
    })
    assert res.status_code == 200
    assert res.body["timings"]["prompt_n"] == 18
    assert res.body["timings"]["predicted_n"] == 8
    assert match_regex("(going|bed)+", res.body["content"])

    # an unknown-to-AR "diffusion_raw" flag must not change anything
    res2 = server.make_request("POST", "/completion", data={
        "n_predict": 8,
        "prompt": "I believe the meaning of life is",
        "seed": 42,
        "diffusion_raw": True,
    })
    assert res2.status_code == 200
    assert res2.body["content"] == res.body["content"]
